# Generated by Django 5.2.7 on 2026-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatto',
            name='contenuto',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='contatto',
            name='email',
            field=models.EmailField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='contatto',
            name='cognome',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='contatto',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
